<?php
/**
 * Altapay Module for Magento 2.x.
 *
 * Copyright © 2018 Altapay. All rights reserved.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>


<?php 
$config = $this->helper('SDM\Altapay\Helper\Config');
$ccFormStyle = !empty($config->ccFormStyle()) ? $config->ccFormStyle() : 'legacy';
?>

<div class="creaditcard-callback-form <?= $ccFormStyle ?>">
    <form id="PensioPaymentForm"></form>
</div>
