<?php
/**
 * Altapay Module for Magento 2.x.
 *
 * Copyright © 2018 Altapay. All rights reserved.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$config = $this->helper('SDM\Altapay\Helper\Config');
$ccFormStyle = $config->ccFormStyle() ?: 'legacy';
$cssClass = ($ccFormStyle === 'checkout_v2') ? 'checkout-v2 checkout' : $ccFormStyle;
?>

<div class="creaditcard-callback-form <?= $cssClass ?>">
    <form id="PensioPaymentForm"></form>
    <div class="surcharge-amount">
        <strong><?= $block->escapeHtml(__('Surcharge:')) ?></strong>
        <span id="PensioSurcharge"></span>
        <span><?= $config->getCurrencySymbol(); ?></span>
    </div>
</div>
