<?php
/**
 * Valitor Module for Magento 2.x.
 *
 * Copyright © 2018 Valitor. All rights reserved.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<?php $collection = $block->getCustomerTokens();
if ($collection->getSize() > 0) {
    ?>
    <div class="table-wrapper orders-history" data-url="<?php echo $block->getAjaxUrl(); ?>">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */
                __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col card"><?= /* @escapeNotVerified */
                    __('Card type') ?></th>
                <th scope="col" class="col card"><?= /* @escapeNotVerified */
                    __('Masked pan') ?></th>
                <th scope="col" class="col expires"><?= /* @escapeNotVerified */
                    __('Expires') ?></th>
                <th scope="col" class="col primary" style="text-align: center;"><?= /* @escapeNotVerified */
                    __('Primary') ?></th>
                <th scope="col" class="col delete" style="text-align: right;"><?= /* @escapeNotVerified */
                    __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($collection as $item): ?>
                <tr id="token-custom-name-status-<?php echo $item->getId(); ?>">
                    <td data-th="CardType" class="col card-type"><?php echo $item->getCardType(); ?></td>
                    <td data-th="CardType" class="col card-type"><?php echo $item->getMaskedPan(); ?></td>
                    <td data-th="CardExpires" class="col card-expiry-date"><?php echo $item->getExpires(); ?></td>
                    <td data-th="Date" class="col created_at" align="center">
                            <span class="token-primay">
                                <input class="token-primay-selection"
                                       type="radio" name="primary-token"
                                       data-token-id="<?php echo $item->getId(); ?>"
                                       value="<?php echo $item->getId(); ?>"
                                       <?php if ($item->getPrimary()) : ?>checked="checked"<?php endif; ?> />
                            </span>
                    </td>
                    <td data-th="Actions" class="col actions" align="right">
                        <button type="button" class="button token-delete" data-token-id="<?php echo $item->getId(); ?>">
                            Delete
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <script type="text/x-magento-init">
	{"*": {"SDM_Valitor/js/Valitor": {}}}



    </script>
<?php } else { ?>
    <div class="message info empty"><span>No saved credit cards.</span></div>
<?php } ?>