
name: PHP Code Analysis

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  php-l:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1']
    steps:
     - name: Install PHP 7.1
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-versions }}
         extensions: intl #optional
         ini-values: "post_max_size=256M" #optional
       
     - run: mkdir plugin-magento2-community
     - uses: actions/checkout@v2 
       with: 
         path: plugin-magento2-community
      
     - name: Run php7.1 linter
       run: |
         find . -path ./vendor -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php7.1 -l -n | (! grep -v "No syntax errors detected" )
       working-directory: plugin-magento2-community
